I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script00.rpy", line 501, in script call
    call dungeon
  File "game/script00.rpy", line 576, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 87, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 108, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 120, in script
    $ current_battle.enemies[0].die()
  File "game/scriptDungeon.rpy", line 120, in <module>
    $ current_battle.enemies[0].die()
AttributeError: 'Doran' object has no attribute 'die'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script00.rpy", line 501, in script call
    call dungeon
  File "game/script00.rpy", line 576, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 87, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 108, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 46, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 120, in script
    $ current_battle.enemies[0].die()
  File "/home/digiholic/workspace/SummonerSweetheart-0.9-all/renpy/ast.py", line 785, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/digiholic/workspace/SummonerSweetheart-0.9-all/renpy/python.py", line 1382, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/scriptDungeon.rpy", line 120, in <module>
    $ current_battle.enemies[0].die()
AttributeError: 'Doran' object has no attribute 'die'

Linux-3.16.0-41-generic-x86_64-with-debian-jessie-sid
Ren'Py 6.18.3.761
Summoner Sweetheart 0.9
